translation_unit_extended :
  global_directive_extended * global_decl *
;

global_directive_extended :
  diagnostic_directive
| enable_directive
| requires_directive
| import_directive
;

import_directive :
  'import' import_path ';'
;

import_path :
  /"[^*"<>:|?\\]+"/
;

translation_unit_import :
  global_directive_import * global_decl *
;

global_directive_import :
  import_directive
;

